import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>Hola Next</h1>

    <Link href="/hola">
      <a>Go to hola</a>
    </Link>
    <br />
    <Link href="/productos">
      <a>Go to productos</a>
    </Link>
      
    </div>
  )
}
